### ISSUE TITLE
Code and Testing do not match

### ISSUE THREAD

**Issue by DerekPeacock** [piniaczchemik/BlueJ-PartA#1]
Hi Kamil

You have a very incomplete Course class which does not match your testing.  Your course class cannot be initialised with a title and codeNo, nor can it print.  Yet your testing says otherwise.

Therefore I have only awarded you 25% for functionality.  Do you have a complete course class anywhere??

**Comment by piniaczchemik** [comment]
Not really sir, still getting familiar with it. Ill get this done as soon
as possible... Already spoke this morning about it with Nick.
